export const countryList = [
{ "name": "Nigeria", "iso_code": "NG", "phone_code": "+234" },
{ "name": "United States", "iso_code": "USA", "phone_code": "+1" },
{ "name": "Canada", "iso_code": "CAD", "phone_code": "+1" },
{ "name": "United Kingdom", "iso_code": "UK", "phone_code": "+44" },
{ "name": "Angola", "iso_code": "AO", "phone_code": "+244" },
{ "name": "Benin", "iso_code": "BJ", "phone_code": "+229" },
{ "name": "Botswana", "iso_code": "BW", "phone_code": "+267" },
{ "name": "Burkina Faso", "iso_code": "BF", "phone_code": "+226" },
{ "name": "Burundi", "iso_code": "BI", "phone_code": "+257" },
{ "name": "Cabo Verde", "iso_code": "CV", "phone_code": "+238" },
{ "name": "Cameroon", "iso_code": "CM", "phone_code": "+237" },
{ "name": "Central African Republic", "iso_code": "CF", "phone_code": "+236" },
{ "name": "Chad", "iso_code": "TD", "phone_code": "+235" },
{ "name": "Comoros", "iso_code": "KM", "phone_code": "+269" },
{ "name": "Republic of the Congo", "iso_code": "CG", "phone_code": "+242" },
{ "name": "Democratic Republic of the Congo", "iso_code": "CD", "phone_code": "+243" },
{ "name": "Djibouti", "iso_code": "DJ", "phone_code": "+253" },
{ "name": "Egypt", "iso_code": "EG", "phone_code": "+20" },
{ "name": "Equatorial Guinea", "iso_code": "GQ", "phone_code": "+240" },
{ "name": "Eritrea", "iso_code": "ER", "phone_code": "+291" },
{ "name": "Eswatini", "iso_code": "SZ", "phone_code": "+268" },
{ "name": "Ethiopia", "iso_code": "ET", "phone_code": "+251" },
{ "name": "Gabon", "iso_code": "GA", "phone_code": "+241" },
{ "name": "Gambia", "iso_code": "GM", "phone_code": "+220" },
{ "name": "Ghana", "iso_code": "GH", "phone_code": "+233" },
{ "name": "Guinea", "iso_code": "GN", "phone_code": "+224" },
{ "name": "Guinea-Bissau", "iso_code": "GW", "phone_code": "+245" },
{ "name": "Ivory Coast", "iso_code": "CI", "phone_code": "+225" },
{ "name": "Kenya", "iso_code": "KE", "phone_code": "+254" },
{ "name": "Lesotho", "iso_code": "LS", "phone_code": "+266" },
{ "name": "Liberia", "iso_code": "LR", "phone_code": "+231" },
{ "name": "Libya", "iso_code": "LY", "phone_code": "+218" },
{ "name": "Madagascar", "iso_code": "MG", "phone_code": "+261" },
{ "name": "Malawi", "iso_code": "MW", "phone_code": "+265" },
{ "name": "Mali", "iso_code": "ML", "phone_code": "+223" },
{ "name": "Mauritania", "iso_code": "MR", "phone_code": "+222" },
{ "name": "Mauritius", "iso_code": "MU", "phone_code": "+230" },
{ "name": "Morocco", "iso_code": "MA", "phone_code": "+212" },
{ "name": "Mozambique", "iso_code": "MZ", "phone_code": "+258" },
{ "name": "Namibia", "iso_code": "NA", "phone_code": "+264" },
{ "name": "Niger", "iso_code": "NE", "phone_code": "+227" },
{ "name": "Rwanda", "iso_code": "RW", "phone_code": "+250" },
{ "name": "São Tomé and Príncipe", "iso_code": "ST", "phone_code": "+239" },
{ "name": "Senegal", "iso_code": "SN", "phone_code": "+221" },
{ "name": "Seychelles", "iso_code": "SC", "phone_code": "+248" },
{ "name": "Sierra Leone", "iso_code": "SL", "phone_code": "+232" },
{ "name": "Somalia", "iso_code": "SO", "phone_code": "+252" },
{ "name": "South Africa", "iso_code": "ZA", "phone_code": "+27" },
{ "name": "South Sudan", "iso_code": "SS", "phone_code": "+211" },
{ "name": "Sudan", "iso_code": "SD", "phone_code": "+249" },
{ "name": "Tanzania", "iso_code": "TZ", "phone_code": "+255" },
{ "name": "Togo", "iso_code": "TG", "phone_code": "+228" },
{ "name": "Tunisia", "iso_code": "TN", "phone_code": "+216" },
{ "name": "Uganda", "iso_code": "UG", "phone_code": "+256" },
{ "name": "Zambia", "iso_code": "ZM", "phone_code": "+260" },
{ "name": "Zimbabwe", "iso_code": "ZW", "phone_code": "+263" }
]